<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\01-Domain\MaktabBookStore.Domain\MaktabBookStore.Domain.csproj" />
    <ProjectReference Include="..\..\03-Infrastructure\MaktabBookStore.Infrastructure.EFCore\MaktabBookStore.Infrastructure.EFCore.csproj" />
  </ItemGroup>

</Project>
